### ISSUE TITLE
How does the readme relate to the code in the repo? 

### ISSUE THREAD

**Issue by geoidesic** [onedesign/express-socketio-tutorial#8]
Hi,

Sounds like a well-described tutorial. However it's not clear what the code in the code repository has to do with the instructions in the README? 

Seems to me if you follow the instructions in the README they don't include checking anything out from github, so the readme is stand-alone. However in that case I would expect the repo to contain the resulting code one would get at the end of the tutorial but looking through the code it doesn't seem that way.

So I'm a bit confused.

**Comment by brianjhanson** [comment]
Hey @geoidesic!

The code in the repo is pretty much the end product of the tutorial which is why you don't need to clone it in order to get going. As stated in the [prerequisites](https://github.com/onedesign/express-socketio-tutorial#prerequisites) section, all you need is node installed and a working knowledge of the command line. Once you have those two checked off, you can follow the tutorial and will more or less create the code housed here. 

Hope that helps!
